namespace VictoryTool.Desktop.Localization;

public sealed record WizardText(
    string Browse,
    string Back,
    string Next,
    string IdentityGameplay,
    string Appearance,
    string Acquisition,
    string Review,
    string ChooseReadableValues,
    string UseCharactersStep,
    string IconWithRearHair,
    string IconWithoutRearHair,
    string PortraitVariantOne,
    string PortraitVariantTwo,
    string DeliveryDefault,
    string SaveMod,
    string PreviewReview,
    string InternalIdentifiersHidden,
    string DeliveryIdsAutomatic,
    string WhatWouldYouLike,
    string CreateNewCharacter,
    string ModifyNewCharacter,
    string ImportIntoVictoryRoad,
    string HowCreate,
    string FromScratch,
    string DuplicateExisting,
    string SelectCharacter,
    string SelectCharacterHint,
    string Search,
    string Clear,
    string Preview,
    string SelectedCharacterData,
    string Affinity,
    string Position,
    string SelectCharacterFromList,
    string UseThisCharacter,
    string CharacterName,
    string GameLanguage,
    string WesternName,
    string JapaneseName,
    string GivenName,
    string FamilyName,
    string ShortName,
    string ShirtName,
    string Description,
    string CharacterAttributes,
    string Gender,
    string OriginGame,
    string AcademicYear,
    string TeamAssociation,
    string MainPosition,
    string SecondaryPosition,
    string CharacterSkills,
    string TechniqueVariant,
    string ApplyTechniqueTemplate,
    string MainSkills,
    string AlternateSkills,
    string UnlockLevel,
    string CharacterAppearance,
    string NormalFace,
    string FaceWithoutRearHair,
    string Model3D,
    string SelectFile,
    string SkinColor,
    string ConfirmCharacter,
    string TechniqueList,
    string SaveCharacter,
    string IncorporationTitle,
    string AddPackage,
    string DropPackage,
    string SaveToBatchQuestion,
    string SaveToBatchYes,
    string SaveToBatchNo,
    string Export,
    string Uniform,
    string Shoes,
    string Gloves,
    string ForceUniform,
    string ForceEquipment,
    string ChestSize,
    string OpenCollar,
    string ExtractedFromPackage,
    string BodyType,
    string Remove,
    string EditLocalesJson)
{
    public static WizardText English { get; } = new(
        "Browse", "Back", "Next", "Identity & Gameplay", "Appearance", "Acquisition", "Review",
        "Choose readable values. Internal identifiers stay hidden.",
        "Use the Characters step to select or duplicate a player, then continue here.",
        "Icon with rear hair", "Icon without rear hair", "Portrait variant 1", "Portrait variant 2",
        "Delivery is selected by default. Shop is optional.", "Save mod", "Preview the export to review the mod.",
        "Internal identifiers stay hidden.", "Delivery IDs are generated automatically and are never reused within the project export.",
        "What would you like to do?", "Create a new character", "Modify a new character", "Import a character into Victory Road",
        "How would you like to create it?", "From scratch", "Duplicate an existing character",
        "Select a character", "Choose the base for your new character. You can edit it afterwards.",
        "Search", "Clear", "Preview", "Selected character data", "Affinity", "Position",
        "Select a character from the list.", "Use this character", "What is the character's name?", "Game language",
        "Western name", "Japanese name", "Given name", "Family name", "Short name", "Shirt name", "Description",
        "Choose character attributes", "Gender", "Origin game", "Academic year", "Team affiliation", "Main position", "Secondary position",
        "Which skills does the character have?", "Technique variant", "Apply this template to all variants", "Main", "Alternate", "Unlock level",
        "What does the character look like?", "Normal face", "Face without rear hair", "3D model", "Browse…",
        "Skin color", "Is everything okay?", "Skill list", "Save",
        "Add characters to the game", "Add package", "Drop a .vrchara here", "Add this character to the incorporation list?", "Yes", "No", "Export",
        "Uniform", "Shoes", "Gloves", "Force uniform", "Force equipment", "Chest size", "Open collar", "Extracted from package", "Body type", "Remove", "Edit locales JSON");

    public static WizardText Spanish { get; } = new(
        "Examinar", "Atrás", "Siguiente", "Identidad y gameplay", "Aspecto", "Obtención", "Revisión",
        "Elige valores legibles. Los identificadores internos quedan ocultos.",
        "Usa el paso Personajes para seleccionar o duplicar un jugador y continúa aquí.",
        "Icono con pelo trasero", "Icono sin pelo trasero", "Variante de retrato 1", "Variante de retrato 2",
        "Delivery está seleccionado por defecto. Tienda es opcional.", "Guardar mod", "Previsualiza la exportación para revisar el mod.",
        "Los identificadores internos quedan ocultos.", "Los IDs de Delivery se generan automáticamente y no se reutilizan en la exportación.",
        "¿Qué quieres hacer?", "Crear un personaje", "Modificar un personaje", "Introducir un personaje",
        "¿Cómo quieres crearlo?", "Desde cero", "Duplicando a uno preexistente",
        "Selecciona al personaje", "Elige la base para tu personaje nuevo. Podrás cambiar sus datos después.",
        "Buscar", "Limpiar", "Vista previa", "Datos del personaje seleccionado", "Afinidad", "Posición",
        "Selecciona un personaje de la lista.", "Usar este personaje", "¿Cómo se llama el personaje?", "Idioma del juego",
        "Nombre occidental", "Nombre en japonés", "Nombre", "Apellido", "Nombre abreviado", "Nombre de camiseta", "Descripción",
        "Selecciona sus atributos", "Género", "Juego de origen", "Año", "Pertenencia de equipo", "Posición principal", "Posición secundaria",
        "¿Qué habilidades tiene?", "Variante de técnicas", "Aplicar esta plantilla a todas las variantes", "Normal", "Alternativo", "Nivel de desbloqueo",
        "¿Y qué aspecto tiene?", "Cara normal", "Cara sin pelo trasero", "Modelo 3D", "Examinar…",
        "Color de piel", "¿Está todo bien?", "Lista de técnicas", "Guardar",
        "Incorpora personajes al juego", "Añadir paquete", "Suelta aquí un .vrchara", "¿Quieres añadir este personaje a la lista de incorporaciones?", "Sí", "No", "Exportar",
        "Uniforme", "Zapatillas", "Guantes", "Forzar uniforme", "Forzar equipamiento", "Tamaño del pecho", "Cuello abierto", "Extraído del paquete", "Tipo corporal", "Eliminar", "Editar JSON de locales");

    public static WizardText ForLocale(string locale) =>
        string.Equals(locale, "es", StringComparison.OrdinalIgnoreCase) ? Spanish : English;
}
